//! The API reference: one JSON file per header for the website, joining the
//! IR's declarations and doc comments with what every binding generates.
//!
//! ```text
//! <out>/index.json         languages + modules with their items (for navigation)
//! <out>/<module>.json      items of one header: docs + per-language signatures
//! ```
//!
//! Signatures come from each generator's `reference()` (see `reference.rs`),
//! C++ from the IR itself, docs from `Api.docs` — all keyed by
//! `codegen_shared::symbols`, so a symbol a binding does not emit simply has no
//! entry for that language.

use std::collections::BTreeMap;
use std::path::Path;

use serde::Serialize;

use codegen_shared::ir::{Api, Class, Doc, Header, Method, Param, TypeRef};
use codegen_shared::{symbols, GeneratedFile, GENERATED_BANNER};

use crate::reference::{Entry, Reference};

/// Languages in display order: `(id, label)`. `cpp` is the core itself.
pub const LANGUAGES: &[(&str, &str)] = &[
    ("cpp", "C++"),
    ("dart", "Dart"),
    ("rust", "Rust"),
    ("csharp", "C#"),
    ("js", "TypeScript"),
    ("python", "Python"),
    ("go", "Go"),
];

#[derive(Serialize)]
struct Index<'a> {
    #[serde(rename = "$comment")]
    comment: String,
    languages: Vec<Language>,
    modules: Vec<ModuleSummary<'a>>,
}

#[derive(Serialize)]
struct Language {
    id: &'static str,
    label: &'static str,
}

#[derive(Serialize)]
struct ModuleSummary<'a> {
    id: &'a str,
    /// Header path relative to `core/src`: `window.h`, `foundation/geometry.h`.
    header: String,
    items: Vec<ItemSummary>,
}

#[derive(Serialize)]
struct ItemSummary {
    key: String,
    kind: &'static str,
    #[serde(skip_serializing_if = "Option::is_none")]
    summary: Option<String>,
    /// Languages that expose this item.
    languages: Vec<&'static str>,
}

#[derive(Serialize)]
struct Module<'a> {
    #[serde(rename = "$comment")]
    comment: String,
    id: &'a str,
    header: String,
    items: Vec<Item>,
}

#[derive(Serialize)]
struct Item {
    key: String,
    /// `class`, `singleton`, `struct`, `enum`, `event`, `alias`.
    kind: &'static str,
    #[serde(skip_serializing_if = "Option::is_none")]
    doc: Option<Doc>,
    signatures: BTreeMap<&'static str, Entry>,
    #[serde(skip_serializing_if = "Vec::is_empty")]
    members: Vec<Member>,
}

#[derive(Serialize)]
struct Member {
    key: String,
    /// `constructor`, `method`, `static`, `listener`, `field`, `constant`,
    /// `variant` (enum value or event type).
    kind: &'static str,
    /// For an event field: the event type it belongs to.
    #[serde(skip_serializing_if = "Option::is_none")]
    parent: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    doc: Option<Doc>,
    signatures: BTreeMap<&'static str, Entry>,
}

pub fn generate(
    api: &Api,
    references: &BTreeMap<&'static str, Reference>,
    src_dir: &Path,
    out: &Path,
) -> Vec<GeneratedFile> {
    let comment = format!(
        "{GENERATED_BANNER} Generated by tools/codegen from the core headers; run ./codegen."
    );
    let mut files = Vec::new();
    let mut summaries = Vec::new();

    for header in &api.headers {
        let header_path = header
            .path
            .strip_prefix(src_dir)
            .unwrap_or(&header.path)
            .to_string_lossy()
            .replace('\\', "/");
        let items = module_items(api, header, references);
        if items.is_empty() {
            continue;
        }
        summaries.push(ModuleSummary {
            id: &header.stem,
            header: header_path.clone(),
            items: items
                .iter()
                .map(|item| ItemSummary {
                    key: item.key.clone(),
                    kind: item.kind,
                    summary: item
                        .doc
                        .as_ref()
                        .map(|doc| doc.summary.clone())
                        .filter(|summary| !summary.is_empty()),
                    languages: item.signatures.keys().copied().collect(),
                })
                .collect(),
        });
        files.push(json_file(
            out.join(format!("{}.json", header.stem)),
            &Module {
                comment: comment.clone(),
                id: &header.stem,
                header: header_path,
                items,
            },
        ));
    }

    files.push(json_file(
        out.join("index.json"),
        &Index {
            comment,
            languages: LANGUAGES
                .iter()
                .map(|&(id, label)| Language { id, label })
                .collect(),
            modules: summaries,
        },
    ));
    files
}

fn json_file(path: std::path::PathBuf, value: &impl Serialize) -> GeneratedFile {
    let mut contents = serde_json::to_string_pretty(value).expect("reference serializes");
    contents.push('\n');
    GeneratedFile { path, contents }
}

fn module_items(
    api: &Api,
    header: &Header,
    references: &BTreeMap<&'static str, Reference>,
) -> Vec<Item> {
    let doc = |key: &str| api.docs.get(key).cloned();
    let signatures = |key: &str, cpp: String| -> BTreeMap<&'static str, Entry> {
        let mut map = BTreeMap::new();
        map.insert(
            "cpp",
            Entry {
                name: key.rsplit("::").next().unwrap_or(key).split('/').next().unwrap_or(key).to_string(),
                signature: cpp,
            },
        );
        for (&lang, reference) in references {
            if let Some(entry) = reference.entries.get(key) {
                map.insert(lang, entry.clone());
            }
        }
        map
    };
    let member = |key: String, kind: &'static str, parent: Option<String>, cpp: String| Member {
        doc: doc(&key),
        signatures: signatures(&key, cpp),
        key,
        kind,
        parent,
    };

    let mut items = Vec::new();

    for class in &header.classes {
        let mut members = Vec::new();
        for (key, ctor) in symbols::constructors(class).into_iter().zip(&class.constructors) {
            let cpp = format!("{}({})", class.name, cpp_params(&ctor.params));
            members.push(member(key, "constructor", None, cpp));
        }
        if let Some(event) = &class.event {
            let cpp = format!(
                "size_t AddListener<{event}>(std::function<void(const {event}&)> listener)"
            );
            members.push(member(symbols::listener(class), "listener", None, cpp));
        }
        for (key, method) in symbols::class_methods(class).into_iter().zip(&class.methods) {
            let kind = if method.is_static && class.is_instance() {
                "static"
            } else {
                "method"
            };
            members.push(member(key, kind, None, cpp_method(method)));
        }
        items.push(Item {
            key: class.name.clone(),
            kind: if class.is_singleton() { "singleton" } else { "class" },
            doc: doc(&class.name),
            signatures: signatures(&class.name, cpp_class(class)),
            members,
        });
    }

    for item in &header.structs {
        let mut members = Vec::new();
        for (key, field) in symbols::struct_fields(item).into_iter().zip(&item.fields) {
            let cpp = format!("{} {}", cpp_type(&field.ty), field.name);
            members.push(member(key, "field", None, cpp));
        }
        for (key, constant) in symbols::struct_constants(item).into_iter().zip(&item.constants) {
            let cpp = format!("static const {} {constant}", item.name);
            members.push(member(key, "constant", None, cpp));
        }
        for (key, method) in symbols::struct_methods(item).into_iter().zip(&item.methods) {
            let kind = if method.is_static { "static" } else { "method" };
            members.push(member(key, kind, None, cpp_method(method)));
        }
        items.push(Item {
            key: item.name.clone(),
            kind: "struct",
            doc: doc(&item.name),
            signatures: signatures(&item.name, format!("struct {}", item.name)),
            members,
        });
    }

    for item in &header.enums {
        let members = symbols::enum_variants(item)
            .into_iter()
            .zip(&item.variants)
            .map(|(key, variant)| {
                member(key, "variant", None, format!("{} = {}", variant.name, variant.value))
            })
            .collect();
        items.push(Item {
            key: item.name.clone(),
            kind: "enum",
            doc: doc(&item.name),
            signatures: signatures(&item.name, format!("enum class {}", cpp_name(&item.qualified_name))),
            members,
        });
    }

    for group in &header.events {
        let mut members = Vec::new();
        for (key, field) in symbols::event_common_fields(group).into_iter().zip(&group.common) {
            members.push(member(key, "field", None, cpp_getter(field)));
        }
        for variant in &group.variants {
            members.push(member(
                variant.name.clone(),
                "variant",
                None,
                format!("class {} : public {}", variant.name, group.name),
            ));
            for (key, field) in symbols::event_variant_fields(variant)
                .into_iter()
                .zip(&variant.fields)
            {
                members.push(member(key, "field", Some(variant.name.clone()), cpp_getter(field)));
            }
        }
        items.push(Item {
            key: group.name.clone(),
            kind: "event",
            doc: doc(&group.name),
            signatures: signatures(&group.name, format!("class {} : public Event", group.name)),
            members,
        });
    }

    for alias in &header.aliases {
        items.push(Item {
            key: alias.name.clone(),
            kind: "alias",
            doc: doc(&alias.name),
            signatures: signatures(
                &alias.name,
                format!("using {} = {}", alias.name, cpp_type(&alias.underlying)),
            ),
            members: Vec::new(),
        });
    }

    items
}

/// `nativeapi::PositioningStrategy::Type` -> `PositioningStrategy::Type`.
fn cpp_name(qualified: &str) -> &str {
    qualified.strip_prefix("nativeapi::").unwrap_or(qualified)
}

fn cpp_class(class: &Class) -> String {
    let mut bases = Vec::new();
    if let Some(base) = &class.base {
        bases.push(format!("public {base}"));
    }
    if let Some(event) = &class.event {
        bases.push(format!("public EventEmitter<{event}>"));
    }
    if bases.is_empty() {
        format!("class {}", class.name)
    } else {
        format!("class {} : {}", class.name, bases.join(", "))
    }
}

fn cpp_method(method: &Method) -> String {
    format!(
        "{}{} {}({}){}",
        if method.is_static { "static " } else { "" },
        cpp_type(&method.return_type),
        method.name,
        cpp_params(&method.params),
        if method.is_const { " const" } else { "" }
    )
}

fn cpp_getter(field: &codegen_shared::ir::Field) -> String {
    format!("{} Get{}() const", cpp_type(&field.ty), field.name)
}

fn cpp_params(params: &[Param]) -> String {
    params
        .iter()
        .map(|param| format!("{} {}", cpp_type(&param.ty), param.name))
        .collect::<Vec<_>>()
        .join(", ")
}

/// C++ spelling of a parameter or return type. Objects cross as
/// `std::shared_ptr` when the header says so.
fn cpp_type(ty: &TypeRef) -> String {
    match ty {
        TypeRef::Object { name, shared: true, .. } => format!("std::shared_ptr<{name}>"),
        TypeRef::Vector { element } => format!("std::vector<{}>", cpp_type(element)),
        TypeRef::Optional { inner } => format!("std::optional<{}>", cpp_type(inner)),
        TypeRef::Enum { qualified_name, .. } | TypeRef::Struct { qualified_name, .. } => {
            cpp_name(qualified_name).to_string()
        }
        other => other.display_name(),
    }
}
