//! Go's public API over cgo. C retains only malloc'd contexts containing
//! runtime/cgo.Handle integers; no Go pointer crosses a callback lifetime.
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;
use std::path::Path;

use codegen_shared::ir::{Api, Class, ClassKind, Constructor, EventGroup, Method, Param, TypeRef};
use codegen_shared::naming::*;
use codegen_shared::GeneratedFile;
use heck::{ToShoutySnakeCase, ToSnakeCase, ToUpperCamelCase};

const PREFIX: &str = "native_";
const BANNER: &str = "// AUTO-GENERATED. DO NOT EDIT.\n// Code generated by ./codegen. DO NOT EDIT.\n// Any manual changes WILL BE LOST when this file is regenerated.\n\n";

fn name(value: &str) -> String {
    value
        .to_snake_case()
        .split('_')
        .map(|part| {
            let letters = part.trim_end_matches(|c: char| c.is_ascii_digit());
            if [
                "acl", "api", "ascii", "cpu", "css", "dns", "eof", "guid", "html", "http", "https",
                "id", "ip", "json", "os", "qps", "ram", "rpc", "sla", "smtp", "sql", "ssh", "tcp",
                "tls", "ttl", "udp", "ui", "uid", "uuid", "uri", "url", "utf", "vm", "xml", "xsrf",
                "xss", "rgba", "argb", "dpi",
            ]
            .contains(&letters)
            {
                part.to_uppercase()
            } else {
                part.to_upper_camel_case()
            }
        })
        .collect()
}
// Public names use Go initialisms; local identifiers use lowerCamelCase.
fn ident(value: &str) -> String {
    let snake = value.to_snake_case();
    let mut parts = snake.split('_');
    let first = parts.next().unwrap_or_default();
    let mut value = first.to_owned();
    for part in parts {
        value.push_str(&name(part));
    }
    match value.as_str() {
        "type" => "kind".into(),
        "default" => "defaultValue".into(),
        // Avoid keywords, predeclared types/functions and the generator's locals.
        "break" | "case" | "chan" | "const" | "continue" | "defer" | "else" | "fallthrough"
        | "for" | "func" | "go" | "goto" | "if" | "import" | "interface" | "map" | "package"
        | "range" | "return" | "select" | "struct" | "switch" | "var" | "bool" | "string"
        | "int" | "uint" | "byte" | "rune" | "error" | "any" | "nil" | "true" | "false" | "new"
        | "make" | "len" | "cap" | "append" | "copy" | "delete" | "close" | "panic" | "recover"
        | "result" | "raw" | "cleanup" | "unsafe" | "cgo" => format!("{value}Value"),
        _ => value,
    }
}
fn receiver(class: &Class, params: &[Param]) -> String {
    let mut value: String = class
        .name
        .to_snake_case()
        .split('_')
        .filter_map(|part| part.chars().next())
        .collect();
    while params.iter().any(|p| ident(&p.name) == value) {
        value.push_str("Obj");
    }
    value
}
fn constructor_name(class: &Class, ctor: &Constructor) -> String {
    let base = format!("New{}", name(&class.name));
    if ctor
        .params
        .iter()
        .any(|p| matches!(p.ty, TypeRef::RawPointer))
    {
        return format!("{base}FromNative");
    }
    let canonical = class
        .constructors
        .iter()
        .find(|c| c.params.is_empty())
        .or_else(|| {
            class
                .constructors
                .iter()
                .find(|c| c.params.iter().any(|p| p.name == "options"))
        })
        .or_else(|| {
            class
                .constructors
                .iter()
                .find(|c| !c.params.iter().any(|p| matches!(p.ty, TypeRef::RawPointer)))
        });
    if canonical == Some(ctor) {
        return base;
    }
    format!(
        "{base}With{}",
        overload_suffix(
            &ctor.params,
            &class
                .constructors
                .iter()
                .map(|c| c.params.as_slice())
                .collect::<Vec<_>>()
        )
    )
}
// Name only the parameter(s) that distinguish an overload. A shared id, offset
// or other common argument need not be repeated in every exported function.
fn overload_suffix(params: &[Param], alternatives: &[&[Param]]) -> String {
    for p in params.iter().rev() {
        if alternatives
            .iter()
            .filter(|other| other.iter().any(|o| o.name == p.name))
            .count()
            == 1
        {
            return name(&p.name);
        }
    }
    params
        .iter()
        .map(|p| name(&p.name))
        .collect::<Vec<_>>()
        .join("And")
}
fn method_name(class: &Class, method: &Method) -> String {
    let base = if method.name == "ToString" && method.params.is_empty() {
        "String"
    } else {
        method.accessor_stem().unwrap_or(&method.name)
    };
    let base = name(base);
    let overloads: Vec<_> = class
        .methods
        .iter()
        .filter(|m| m.name == method.name)
        .collect();
    if overloads.len() < 2 || method.params.is_empty() {
        return base;
    }
    if method.params.iter().any(|p| p.name == "options") {
        return base;
    }
    let suffix = overload_suffix(
        &method.params,
        &overloads
            .iter()
            .map(|m| m.params.as_slice())
            .collect::<Vec<_>>(),
    );
    let preposition = match method.name.as_str() {
        "Get" | "Unregister" => "By",
        "Relative" => "To",
        _ => "With",
    };
    format!("{base}{preposition}{suffix}")
}
fn bool_is_error(method: &Method) -> bool {
    let predicate = ["Is", "Has", "Can", "Contains"].iter().any(|prefix| {
        method
            .name
            .strip_prefix(prefix)
            .is_some_and(|rest| rest.is_empty() || rest.starts_with(char::is_uppercase))
    });
    matches!(method.return_type, TypeRef::Bool) && !predicate
}
fn object_is_error(class: &Class, method: &Method) -> bool {
    matches!(method.return_type, TypeRef::Object { .. })
        && (method.is_static || class.is_singleton() && method.name == "Register")
}
fn result_type(class: &Class, method: &Method) -> String {
    if bool_is_error(method) {
        "error".into()
    } else if object_is_error(class, method) {
        format!("({}, error)", ty(&method.return_type))
    } else {
        ty(&method.return_type)
    }
}
fn cty(ty: &TypeRef) -> String {
    let raw = c_field_type(ty, PREFIX);
    format!(
        "C.{}",
        match raw.as_str() {
            "unsigned char" => "uchar",
            "signed char" => "schar",
            "unsigned short" => "ushort",
            "unsigned int" => "uint",
            "unsigned long" => "ulong",
            "unsigned long long" => "ulonglong",
            "long long" => "longlong",
            other => other,
        }
    )
}
fn ty(t: &TypeRef) -> String {
    match t {
        TypeRef::Void => String::new(),
        TypeRef::Bool => "bool".into(),
        TypeRef::Int { name } => match name.as_str() {
            "char" | "signed char" => "int8",
            "unsigned char" => "uint8",
            "short" => "int16",
            "unsigned short" => "uint16",
            "int" => "int32",
            "unsigned int" => "uint32",
            "unsigned long" | "unsigned long long" | "uint64_t" | "size_t" => "uint64",
            _ => "int64",
        }
        .into(),
        TypeRef::Float { name } => if name == "float" {
            "float32"
        } else {
            "float64"
        }
        .into(),
        TypeRef::String | TypeRef::CString => "string".into(),
        TypeRef::Enum { name: n, .. }
        | TypeRef::Struct { name: n, .. }
        | TypeRef::Alias { name: n, .. } => name(n),
        TypeRef::Object { name: n, .. } => format!("*{}", name(n)),
        TypeRef::Vector { element } => format!("[]{}", ty(element)),
        TypeRef::Map { .. } => "map[string]string".into(),
        TypeRef::Optional { inner } => match inner.as_ref() {
            TypeRef::String | TypeRef::CString | TypeRef::Struct { .. } => {
                format!("*{}", ty(inner))
            }
            _ => ty(inner),
        },
        TypeRef::Callback { params } => format!(
            "func({})",
            params.iter().map(ty).collect::<Vec<_>>().join(", ")
        ),
        TypeRef::RawPointer => "unsafe.Pointer".into(),
        TypeRef::Unsupported { name } => panic!("unsupported Go type: {name}"),
    }
}
fn field(value: &str) -> String {
    let value = value.to_snake_case();
    if [
        "type",
        "range",
        "map",
        "func",
        "interface",
        "select",
        "chan",
        "var",
        "const",
        "default",
        "go",
        "defer",
        "return",
        "struct",
        "switch",
        "case",
        "break",
        "continue",
        "else",
        "fallthrough",
        "for",
        "goto",
        "if",
        "import",
        "package",
    ]
    .contains(&value.as_str())
    {
        format!("_{value}")
    } else {
        value
    }
}

// Conversion of borrowed payloads. Owning returns are freed by the caller
// after conversion, and handles in owning lists are transferred separately.
fn from_c(t: &TypeRef, value: &str, borrowed: bool) -> String {
    match t {
        TypeRef::Void => String::new(),
        TypeRef::String | TypeRef::CString => format!("C.GoString({value})"),
        TypeRef::Struct { name: n, .. } => format!("fromC{}({value})", name(n)),
        TypeRef::Object { name: n, .. } => format!("wrap{}(uint64({value}), {borrowed})", name(n)),
        TypeRef::RawPointer => value.to_owned(),
        TypeRef::Vector { element } => match element.as_ref() {
            TypeRef::String => format!("stringsFromC({value})"),
            TypeRef::Object { name: n, .. } => format!("list{}FromC({value}, {borrowed})", name(n)),
            _ => panic!("unsupported Go list element"),
        },
        TypeRef::Map { .. } => format!("mapFromC({value})"),
        TypeRef::Optional { inner } => match inner.as_ref() {
            TypeRef::String | TypeRef::CString => format!("optionalStringFromC({value})"),
            _ => from_c(inner, value, borrowed),
        },
        _ => format!("{}({value})", ty(t)),
    }
}

// Produces C arguments and scopes temporary C allocations to the enclosing
// call. Callback contexts are transferred to the C ABI, which releases them.
fn cleanup(out: &mut String, call: &str, deferred: bool) {
    if deferred {
        writeln!(out, "defer {call}").unwrap();
    } else {
        writeln!(out, "cleanup = append(cleanup, func() {{ {call} }})").unwrap();
    }
}
fn to_c(
    out: &mut String,
    t: &TypeRef,
    value: &str,
    local: &str,
    callback: &str,
    deferred: bool,
) -> Vec<String> {
    if is_callback(t) {
        writeln!(out, "var {local}Fn C.{callback}\nvar {local}Data unsafe.Pointer\nvar {local}Release C.native_release_user_data_t\nif {value} != nil {{\n{local}Data = newCallback({value})\n{local}Fn = C.{callback}(C.go_get_{callback}())\n{local}Release = C.native_release_user_data_t(C.go_get_release_callback())\n}}").unwrap();
        return vec![
            format!("{local}Fn"),
            format!("{local}Data"),
            format!("{local}Release"),
        ];
    }
    let expr = match t {
        TypeRef::String | TypeRef::CString => {
            writeln!(out, "{local} := C.CString({value})").unwrap();
            cleanup(out, &format!("C.free(unsafe.Pointer({local}))"), deferred);
            local.to_owned()
        }
        TypeRef::Optional { inner } => match inner.as_ref() {
            TypeRef::String | TypeRef::CString => {
                writeln!(
                    out,
                    "var {local} *C.char\nif {value} != nil {{ {local} = C.CString(*{value})"
                )
                .unwrap();
                cleanup(out, &format!("C.free(unsafe.Pointer({local}))"), deferred);
                writeln!(out, "}}").unwrap();
                local.to_owned()
            }
            TypeRef::Struct { name: n, .. } => {
                writeln!(out,"var {local} *C.{}\nif {value} != nil {{ temp, {local}Cleanup := toC{}(*{value}); {local} = &temp",c_type_name(PREFIX,n),name(n)).unwrap();
                cleanup(out, &format!("{local}Cleanup()"), deferred);
                writeln!(out, "}}").unwrap();
                local.to_owned()
            }
            other => return to_c(out, other, value, local, callback, deferred),
        },
        TypeRef::Struct { name: n, .. } => {
            writeln!(out, "{local}, {local}Cleanup := toC{}({value})", name(n)).unwrap();
            cleanup(out, &format!("{local}Cleanup()"), deferred);
            local.to_owned()
        }
        TypeRef::Object { .. } => format!("{}({value}.nativeHandleValue())", cty(t)),
        TypeRef::Vector { element } if matches!(element.as_ref(), TypeRef::String) => {
            writeln!(out, "{local}, {local}Cleanup := stringsToC({value})").unwrap();
            cleanup(out, &format!("{local}Cleanup()"), deferred);
            local.to_owned()
        }
        TypeRef::RawPointer => value.to_owned(),
        _ => format!("{}({value})", cty(t)),
    };
    vec![expr]
}

fn params(params: &[Param]) -> String {
    let mut groups = Vec::new();
    let mut names = Vec::new();
    let mut previous = String::new();
    for param in params {
        let current = ty(&param.ty);
        if !names.is_empty() && current != previous {
            groups.push(format!("{} {previous}", names.join(", ")));
            names.clear();
        }
        names.push(ident(&param.name));
        previous = current;
    }
    if !names.is_empty() {
        groups.push(format!("{} {previous}", names.join(", ")));
    }
    groups.join(", ")
}
fn arguments(out: &mut String, p: &[Param], owner: &str, member: &str) -> Vec<String> {
    p.iter()
        .enumerate()
        .flat_map(|(i, p)| {
            to_c(
                out,
                &p.ty,
                &ident(&p.name),
                &format!("cArg{i}"),
                &c_callback_type_name(PREFIX, owner, member),
                true,
            )
        })
        .collect()
}
fn return_value(
    out: &mut String,
    api: &Api,
    t: &TypeRef,
    call: &str,
    error: bool,
    operation: &str,
) {
    if matches!(t, TypeRef::Void) {
        writeln!(out, "{call}").unwrap();
        return;
    }
    writeln!(out, "result := {call}").unwrap();
    match t.unwrap_optional() {
        TypeRef::String | TypeRef::CString => {
            writeln!(out, "defer C.free_c_str(result)").unwrap();
        }
        TypeRef::Struct { name, .. } => {
            if api
                .headers
                .iter()
                .flat_map(|h| &h.structs)
                .any(|s| s.name == *name && struct_has_owned_fields(s))
            {
                writeln!(out, "defer C.{}(&result)", c_free_symbol(PREFIX, name)).unwrap();
            }
        }
        TypeRef::Vector { element } => {
            let free = match element.as_ref() {
                TypeRef::String => STRING_LIST_FREE_FN.to_owned(),
                TypeRef::Object { name, .. } => c_list_release_symbol(PREFIX, name),
                _ => panic!("unsupported Go list return"),
            };
            writeln!(out, "defer C.{free}(&result)").unwrap();
        }
        TypeRef::Map { .. } => {
            writeln!(out, "defer C.native_string_map_free(&result)").unwrap();
        }
        _ => (),
    }
    if error {
        if matches!(t, TypeRef::Bool) {
            writeln!(
                out,
                "if !bool(result) {{ return nativeError(\"{operation}\") }}\nreturn nil"
            )
            .unwrap();
        } else {
            writeln!(
                out,
                "if result == 0 {{ return nil, nativeError(\"{operation}\") }}\nreturn {}, nil",
                from_c(t, "result", false)
            )
            .unwrap();
        }
    } else {
        writeln!(out, "return {}", from_c(t, "result", false)).unwrap();
    }
}

struct Callback {
    c_name: String,
    params: Vec<TypeRef>,
}
fn callback_bridge(out: &mut String, bridge: &mut String, cb: &Callback) {
    let n = &cb.c_name;
    let declarations = cb
        .params
        .iter()
        .enumerate()
        .map(|(i, t)| format!("{} arg{i}", c_param_type(t, PREFIX)))
        .collect::<Vec<_>>();
    let mut c_args = declarations.clone();
    c_args.push("void* data".into());
    let mut go_args = vec!["uintptr_t handle".to_owned()];
    go_args.extend(declarations);
    // None of the API's ordinary callbacks currently carries a const pointer.
    writeln!(bridge,"extern void goCall_{n}({});\nstatic inline void go_{n}({}) {{ goCall_{n}(*(uintptr_t*)data{}); }}",go_args.join(", "),c_args.join(", "),cb.params.iter().enumerate().map(|(i,_)|format!(", arg{i}")).collect::<String>()).unwrap();
    writeln!(
        bridge,
        "static inline {n} go_get_{n}(void) {{ return go_{n}; }}"
    )
    .unwrap();
    let mut go_params = vec!["handle C.uintptr_t".to_owned()];
    go_params.extend(
        cb.params
            .iter()
            .enumerate()
            .map(|(i, t)| format!("arg{i} {}", cty(t))),
    );
    writeln!(
        out,
        "//export goCall_{n}\nfunc goCall_{n}({}) {{\ncgo.Handle(handle).Value().({})({})\n}}",
        go_params.join(", "),
        ty(&TypeRef::Callback {
            params: cb.params.clone()
        }),
        cb.params
            .iter()
            .enumerate()
            .map(|(i, t)| from_c(t, &format!("arg{i}"), true))
            .collect::<Vec<_>>()
            .join(", ")
    )
    .unwrap();
}

fn events(out: &mut String, bridge: &mut String, group: &EventGroup) {
    let gn = name(&group.name);
    let cn = c_type_name(PREFIX, &group.name);
    writeln!(
        out,
        "// {gn}Type identifies the active event variant.\ntype {gn}Type int32\nconst ("
    )
    .unwrap();
    for (i, v) in group.variants.iter().enumerate() {
        writeln!(out, "{gn}{} {gn}Type = {i}", name(&v.discriminant)).unwrap();
    }
    writeln!(out,")\n// {gn} copies an event payload. Handle fields are borrowed until the callback returns.\n// Only fields belonging to Type are populated.\ntype {gn} struct {{\nType {gn}Type").unwrap();
    let mut seen = BTreeMap::new();
    for f in group
        .common
        .iter()
        .chain(group.variants.iter().flat_map(|v| &v.fields))
    {
        if let Some(t) = seen.insert(f.name.clone(), f.ty.clone()) {
            assert_eq!(t, f.ty, "conflicting Go event fields");
            continue;
        }
        writeln!(out, "{} {}", name(&f.name), ty(&f.ty)).unwrap();
    }
    writeln!(
        out,
        "}}\nfunc fromC{gn}(raw *C.{cn}) {gn} {{\nvalue := {gn}{{Type: {gn}Type(raw._type)}}"
    )
    .unwrap();
    for f in &group.common {
        writeln!(
            out,
            "value.{} = {}",
            name(&f.name),
            from_c(&f.ty, &format!("raw.{}", field(&f.name)), true)
        )
        .unwrap();
    }
    writeln!(out, "switch value.Type {{").unwrap();
    for v in &group.variants {
        writeln!(out, "case {gn}{}:", name(&v.discriminant)).unwrap();
        for f in &v.fields {
            let helper = format!(
                "go_{cn}_{}_{}",
                c_event_variant_field(&v.discriminant),
                f.name
            );
            writeln!(
                bridge,
                "static inline {} {helper}(const {cn}* event) {{ return event->data.{}.{}; }}",
                c_field_type(&f.ty, PREFIX),
                c_event_variant_field(&v.discriminant),
                f.name.to_snake_case()
            )
            .unwrap();
            writeln!(
                out,
                "value.{} = {}",
                name(&f.name),
                from_c(&f.ty, &format!("C.{helper}(raw)"), true)
            )
            .unwrap();
        }
    }
    writeln!(out, "}}\nreturn value\n}}").unwrap();
    let cb = c_event_callback_type(PREFIX, &group.name);
    writeln!(bridge,"extern void goEvent_{cn}(uintptr_t handle, {cn}* event);\nstatic inline void go_{cb}(const {cn}* event, void* data) {{ goEvent_{cn}(*(uintptr_t*)data, ({cn}*)event); }}").unwrap();
    writeln!(
        bridge,
        "static inline {cb} go_get_{cb}(void) {{ return go_{cb}; }}"
    )
    .unwrap();
    writeln!(out,"//export goEvent_{cn}\nfunc goEvent_{cn}(handle C.uintptr_t, event *C.{cn}) {{\ncgo.Handle(handle).Value().(func({gn}))(fromC{gn}(event))\n}}").unwrap();
}

fn class(out: &mut String, api: &Api, c: &Class) {
    let n = name(&c.name);
    let cn = c_type_name(PREFIX, &c.name);
    let recv = receiver(c, &[]);
    let singleton_type = ident(&c.name);
    if c.is_singleton() {
        writeln!(out, "type {singleton_type} struct {{}}\n// {n} provides access to the native {n} singleton.\n// It has no owned handle and does not need to be released.\nvar {n} = {singleton_type}{{}}\n").unwrap();
    }
    if c.is_instance() {
        let member = c
            .base
            .as_ref()
            .map(|b| name(b))
            .unwrap_or_else(|| "nativeHandle".into());
        writeln!(out,"// {n} owns a native handle. Call Release on the UI thread when done.\n// Copies share ownership state; borrowed event handles must not outlive their callback.\ntype {n} struct {{ *{member} }}\nfunc wrap{n}(value uint64, borrowed bool) *{n} {{\nif value == 0 {{ return nil }}\nreturn wrap{n}State(&nativeHandle{{value: value, borrowed: borrowed}})\n}}\nfunc wrap{n}State(state *nativeHandle) *{n} {{").unwrap();
        if let Some(base) = &c.base {
            writeln!(out, "return &{n}{{wrap{}State(state)}}", name(base)).unwrap();
        } else {
            writeln!(out, "return &{n}{{state}}").unwrap();
        }
        writeln!(out,"}}\nfunc ({recv} *{n}) nativeHandleValue() uint64 {{\nif {recv} == nil || {recv}.{member} == nil {{ return 0 }}\nreturn {recv}.{member}.nativeHandleValue()\n}}\n// Release drops this owned reference. Repeated calls and nil receivers are safe.\nfunc ({recv} *{n}) Release() {{\nif {recv}.nativeHandleValue() == 0 || {recv}.borrowed {{ return }}\nC.{}(C.{cn}({recv}.value))\n{recv}.value = 0\n}}",c_free_symbol(PREFIX,&c.name)).unwrap();
    }
    let mut exported = BTreeSet::new();
    for ctor in &c.constructors {
        let function = constructor_name(c, ctor);
        assert!(
            exported.insert(function.clone()),
            "Go constructor collision: {function}"
        );
        writeln!(out, "// {function} creates an owned {n}.\n// Failure wraps ErrOperationFailed; the native ABI provides no detailed cause.\nfunc {function}({}) (*{n}, error) {{", params(&ctor.params)).unwrap();
        let symbol = c_constructor_symbol(PREFIX, c, ctor);
        let member = symbol
            .strip_prefix(&format!("native_{}_", c.name.to_snake_case()))
            .unwrap();
        let args = arguments(out, &ctor.params, &c.name, member);
        writeln!(out, "result := C.{symbol}({})\nif result == 0 {{ return nil, nativeError(\"{function}\") }}\nreturn wrap{n}(uint64(result), false), nil\n}}",args.join(", ")).unwrap();
    }
    for m in &c.methods {
        if !m.return_type.is_supported() || !m.params.iter().all(|p| p.ty.is_supported()) {
            continue;
        }
        let mn = method_name(c, m);
        let instance = c.is_instance() && !m.is_static;
        let function = if instance || c.is_singleton() {
            mn.clone()
        } else {
            format!("{n}{mn}")
        };
        assert!(
            exported.insert(function.clone()),
            "Go method collision: {n}.{function}"
        );
        let recv = receiver(c, &m.params);
        writeln!(
            out,
            "// {function} invokes the native {} operation.",
            m.name
        )
        .unwrap();
        if bool_is_error(m) || object_is_error(c, m) {
            writeln!(
                out,
                "// Failure wraps ErrOperationFailed; the native ABI provides no detailed cause."
            )
            .unwrap();
        } else if matches!(m.return_type, TypeRef::Object { .. }) {
            writeln!(
                out,
                "// The returned reference is owned; nil means no object is available."
            )
            .unwrap();
        }
        if instance {
            write!(out, "func ({recv} *{n}) {function}(").unwrap();
        } else if c.is_singleton() {
            write!(out, "func ({recv} {singleton_type}) {function}(").unwrap();
        } else {
            write!(out, "func {function}(").unwrap();
        }
        writeln!(out, "{}) {} {{", params(&m.params), result_type(c, m)).unwrap();
        let mut args = Vec::new();
        if instance {
            args.push(format!("C.{cn}({recv}.nativeHandleValue())"));
        }
        args.extend(arguments(out, &m.params, &c.name, &m.name));
        return_value(
            out,
            api,
            &m.return_type,
            &format!("C.{}({})", c_method_symbol(PREFIX, c, m), args.join(", ")),
            bool_is_error(m) || object_is_error(c, m),
            &if instance || c.is_singleton() {
                format!("{n}.{function}")
            } else {
                function.clone()
            },
        );
        writeln!(out, "}}").unwrap();
    }
    if c.native_object {
        writeln!(out,"// NativeObject returns a borrowed platform pointer.\nfunc ({recv} *{n}) NativeObject() unsafe.Pointer {{ return C.{}(C.{cn}({recv}.nativeHandleValue())) }}",c_native_object_symbol(PREFIX,&c.name)).unwrap();
    }
    if let Some(event) = &c.event {
        let en = name(event);
        let cb = c_event_callback_type(PREFIX, event);
        let receiver = if c.is_instance() {
            format!("({recv} *{n}) ")
        } else {
            format!("({recv} {singleton_type}) ")
        };
        let prefix = "";
        let handle = if c.is_instance() {
            format!("C.{cn}({recv}.nativeHandleValue()), ")
        } else {
            String::new()
        };
        let operation = format!("{n}.");
        writeln!(out,"// {prefix}AddListener invokes callback synchronously on the native UI thread.\n// Remove the listener before releasing its owner. A nil callback is invalid.\nfunc {receiver}{prefix}AddListener(callback func({en})) (ListenerID, error) {{\nif callback == nil {{ return 0, invalidArgument(\"{operation}AddListener\") }}\ndata := newCallback(callback)\nid := C.{}({handle}C.{cb}(C.go_get_{cb}()), data, C.native_release_user_data_t(C.go_get_release_callback()))\nif id == 0 {{ return 0, nativeError(\"{operation}AddListener\") }}\nreturn ListenerID(id), nil\n}}\n// {prefix}RemoveListener unregisters id; an unknown id returns an error.\nfunc {receiver}{prefix}RemoveListener(id ListenerID) error {{\nif !bool(C.{}({handle}C.native_listener_id_t(id))) {{ return nativeError(\"{operation}RemoveListener\") }}\nreturn nil\n}}",c_add_listener_symbol(PREFIX,&c.name),c_remove_listener_symbol(PREFIX,&c.name)).unwrap();
    }
}

pub fn generate(api: &Api, out_dir: &Path) -> Vec<GeneratedFile> {
    let mut out = format!("{BANNER}package nativeapi\n\n/*\n#include \"bridge.gen.h\"\n*/\nimport \"C\"\nimport (\"runtime/cgo\"; \"unsafe\")\n\n");
    let mut bridge = format!("{BANNER}#pragma once\n#include \"nativeapi.h\"\n#include <stdlib.h>\n#include <stdint.h>\nextern void goReleaseCallback(uintptr_t handle);\nstatic inline void go_release_callback(void* data) {{\nif (data) {{ goReleaseCallback(*(uintptr_t*)data); free(data); }}\n}}\n");
    bridge.push_str("static inline native_release_user_data_t go_get_release_callback(void) { return go_release_callback; }\n");
    let mut callbacks = BTreeMap::new();
    let mut seen_aliases = BTreeSet::new();
    for h in &api.headers {
        for a in &h.aliases {
            if seen_aliases.insert(&a.name) {
                writeln!(
                    out,
                    "// {} identifies a native object.\ntype {} {}",
                    name(&a.name),
                    name(&a.name),
                    ty(&a.underlying)
                )
                .unwrap();
            }
        }
        for e in &h.enums {
            writeln!(
                out,
                "// {} represents native {} values.\ntype {} int32\nconst (",
                name(&e.name),
                e.name,
                name(&e.name)
            )
            .unwrap();
            for v in &e.variants {
                writeln!(
                    out,
                    "{}{} {} = {}",
                    name(&e.name),
                    name(v.name.strip_prefix('k').unwrap_or(&v.name)),
                    name(&e.name),
                    v.value
                )
                .unwrap();
            }
            writeln!(out, ")").unwrap();
        }
        for s in &h.structs {
            let n = name(&s.name);
            let cn = c_type_name(PREFIX, &s.name);
            writeln!(
                out,
                "// {n} holds the native {} value.\ntype {n} struct {{",
                s.name
            )
            .unwrap();
            for f in &s.fields {
                writeln!(out, "{} {}", name(&f.name), ty(&f.ty)).unwrap();
            }
            writeln!(out, "}}\nfunc fromC{n}(raw C.{cn}) {n} {{\nreturn {n}{{").unwrap();
            for f in &s.fields {
                if is_callback(&f.ty) {
                    continue;
                }
                writeln!(
                    out,
                    "{}: {},",
                    name(&f.name),
                    from_c(&f.ty, &format!("raw.{}", field(&f.name)), true)
                )
                .unwrap();
            }
            writeln!(out,"}}\n}}\nfunc toC{n}(value {n}) (C.{cn}, func()) {{\nvar raw C.{cn}\nvar cleanup []func()").unwrap();
            for (i, f) in s.fields.iter().enumerate() {
                let cb = c_callback_type_name(PREFIX, &s.name, &f.name);
                let args = to_c(
                    &mut out,
                    &f.ty,
                    &format!("value.{}", name(&f.name)),
                    &format!("cField{i}"),
                    &cb,
                    false,
                );
                writeln!(out, "raw.{} = {}", field(&f.name), args[0]).unwrap();
                if is_callback(&f.ty) {
                    writeln!(
                        out,
                        "raw.{}_user_data = {}\nraw.{}_release_user_data = {}",
                        f.name, args[1], f.name, args[2]
                    )
                    .unwrap();
                    if let TypeRef::Callback { params } = f.ty.unwrap_optional() {
                        callbacks.insert(
                            cb.clone(),
                            Callback {
                                c_name: cb,
                                params: params.clone(),
                            },
                        );
                    }
                }
            }
            writeln!(out,"return raw, func() {{ for i := len(cleanup)-1; i >= 0; i-- {{ cleanup[i]() }} }}\n}}").unwrap();
            let pseudo = Class {
                name: s.name.clone(),
                qualified_name: s.qualified_name.clone(),
                kind: ClassKind::Instance,
                native_object: false,
                constructors: vec![],
                methods: s.methods.clone(),
                event: None,
                base: None,
            };
            for m in &s.methods {
                let mn = method_name(&pseudo, m);
                let recv = receiver(&pseudo, &m.params);
                let function = if m.is_static {
                    format!("{n}{mn}")
                } else {
                    mn.clone()
                };
                writeln!(
                    out,
                    "// {function} invokes the native {} operation.",
                    m.name
                )
                .unwrap();
                if m.is_static {
                    write!(out, "func {function}(").unwrap();
                } else {
                    write!(out, "func ({recv} {n}) {function}(").unwrap();
                }
                writeln!(out, "{}) {} {{", params(&m.params), result_type(&pseudo, m)).unwrap();
                let mut args = Vec::new();
                if !m.is_static {
                    args.extend(to_c(
                        &mut out,
                        &TypeRef::Struct {
                            name: s.name.clone(),
                            qualified_name: s.qualified_name.clone(),
                        },
                        &recv,
                        "cSelf",
                        "",
                        true,
                    ));
                }
                args.extend(arguments(&mut out, &m.params, &s.name, &m.name));
                return_value(
                    &mut out,
                    api,
                    &m.return_type,
                    &format!(
                        "C.{}({})",
                        c_method_symbol(PREFIX, &pseudo, m),
                        args.join(", ")
                    ),
                    bool_is_error(m) || object_is_error(&pseudo, m),
                    &format!("{n}.{mn}"),
                );
                writeln!(out, "}}").unwrap();
            }
            for constant in &s.constants {
                writeln!(
                    out,
                    "// {n}{} is the native {} value.\nvar {n}{} = fromC{n}(C.NATIVE_{}_{})",
                    name(constant),
                    constant.to_snake_case(),
                    name(constant),
                    s.name.to_shouty_snake_case(),
                    constant.to_shouty_snake_case()
                )
                .unwrap();
            }
        }
        for group in &h.events {
            events(&mut out, &mut bridge, group);
        }
        for c in &h.classes {
            class(&mut out, api, c);
            for ctor in &c.constructors {
                let sym = c_constructor_symbol(PREFIX, c, ctor);
                let member = sym
                    .strip_prefix(&format!("native_{}_", c.name.to_snake_case()))
                    .unwrap();
                collect_callbacks(&mut callbacks, &ctor.params, &c.name, member);
            }
            for m in &c.methods {
                collect_callbacks(&mut callbacks, &m.params, &c.name, &m.name);
            }
        }
    }
    for n in listed_classes(api) {
        let gn = name(&n);
        let cn = c_list_type_name(PREFIX, &n);
        let f = c_list_field(&n);
        writeln!(out,"func list{gn}FromC(raw C.{cn}, borrowed bool) []*{gn} {{\nresult := make([]*{gn}, int(raw.count))\nfor i, handle := range unsafe.Slice(raw.{f}, int(raw.count)) {{ result[i] = wrap{gn}(uint64(handle), borrowed) }}\nreturn result\n}}").unwrap();
    }
    for cb in callbacks.values() {
        callback_bridge(&mut out, &mut bridge, cb);
    }
    vec![
        GeneratedFile {
            path: out_dir.join("nativeapi.gen.go"),
            contents: out,
        },
        GeneratedFile {
            path: out_dir.join("bridge.gen.h"),
            contents: bridge,
        },
    ]
}
fn collect_callbacks(
    callbacks: &mut BTreeMap<String, Callback>,
    params: &[Param],
    owner: &str,
    member: &str,
) {
    for p in params {
        if let TypeRef::Callback { params } = p.ty.unwrap_optional() {
            let n = c_callback_type_name(PREFIX, owner, member);
            callbacks.insert(
                n.clone(),
                Callback {
                    c_name: n,
                    params: params.clone(),
                },
            );
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn go_initialisms_and_keywords() {
        assert_eq!(name("WindowId"), "WindowID");
        assert_eq!(name("FromRGBA"), "FromRGBA");
        assert_eq!(name("GetOsName"), "GetOSName");
        assert_eq!(name("WinUI3"), "WinUI3");
        assert_eq!(ident("type"), "kind");
        assert_eq!(ident("window_id"), "windowID");
        assert_eq!(ident("default_value"), "defaultValue");
        assert_eq!(field("type"), "_type");
    }
    #[test]
    fn optional_strings_preserve_absence() {
        let t = TypeRef::Optional {
            inner: Box::new(TypeRef::String),
        };
        assert_eq!(ty(&t), "*string");
        assert_eq!(from_c(&t, "value", false), "optionalStringFromC(value)");
    }
    #[test]
    fn singleton_uses_methods_without_native_receiver() {
        let manager = Class {
            name: "DisplayManager".into(),
            qualified_name: "nativeapi::DisplayManager".into(),
            kind: ClassKind::Singleton,
            native_object: false,
            constructors: vec![],
            methods: vec![
                Method {
                    name: "GetAll".into(),
                    return_type: TypeRef::Vector {
                        element: Box::new(TypeRef::String),
                    },
                    params: vec![],
                    is_const: true,
                    is_static: false,
                },
                Method {
                    name: "Refresh".into(),
                    return_type: TypeRef::Bool,
                    params: vec![],
                    is_const: false,
                    is_static: true,
                },
            ],
            event: Some("DisplayEvent".into()),
            base: None,
        };
        let mut out = String::new();
        class(
            &mut out,
            &Api {
                headers: vec![],
                diagnostics: vec![],
            },
            &manager,
        );
        assert!(out.contains("var DisplayManager = displayManager{}"));
        assert!(out.contains("func (dm displayManager) All() []string"));
        assert!(out.contains("C.native_display_manager_get_all()"));
        assert!(out.contains("func (dm displayManager) Refresh() error"));
        assert!(out.contains("nativeError(\"DisplayManager.Refresh\")"));
        assert!(out.contains("func (dm displayManager) AddListener("));
        assert!(out.contains("invalidArgument(\"DisplayManager.AddListener\")"));
        assert!(out.contains("func (dm displayManager) RemoveListener("));
        assert!(!out.contains("func DisplayManagerAll"));
        assert!(!out.contains("nativeHandleValue"));
    }
}
