/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as LocaleSupportRouteImport } from './routes/$locale_.support'
import { Route as LocaleDocsIndexRouteImport } from './routes/$locale_.docs.index'
import { Route as LocaleDocsSplatRouteImport } from './routes/$locale_.docs.$'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSupportRoute = LocaleSupportRouteImport.update({
  id: '/$locale_/support',
  path: '/$locale/support',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleDocsIndexRoute = LocaleDocsIndexRouteImport.update({
  id: '/$locale_/docs/',
  path: '/$locale/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleDocsSplatRoute = LocaleDocsSplatRouteImport.update({
  id: '/$locale_/docs/$',
  path: '/$locale/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRoute
  '/support': typeof SupportRoute
  '/$locale/support': typeof LocaleSupportRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/': typeof DocsIndexRoute
  '/$locale/docs/$': typeof LocaleDocsSplatRoute
  '/$locale/docs/': typeof LocaleDocsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRoute
  '/support': typeof SupportRoute
  '/$locale/support': typeof LocaleSupportRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs': typeof DocsIndexRoute
  '/$locale/docs/$': typeof LocaleDocsSplatRoute
  '/$locale/docs': typeof LocaleDocsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRoute
  '/support': typeof SupportRoute
  '/$locale_/support': typeof LocaleSupportRoute
  '/docs/$': typeof DocsSplatRoute
  '/docs/': typeof DocsIndexRoute
  '/$locale_/docs/$': typeof LocaleDocsSplatRoute
  '/$locale_/docs/': typeof LocaleDocsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/support'
    | '/$locale/support'
    | '/docs/$'
    | '/docs/'
    | '/$locale/docs/$'
    | '/$locale/docs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/support'
    | '/$locale/support'
    | '/docs/$'
    | '/docs'
    | '/$locale/docs/$'
    | '/$locale/docs'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/support'
    | '/$locale_/support'
    | '/docs/$'
    | '/docs/'
    | '/$locale_/docs/$'
    | '/$locale_/docs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRoute
  SupportRoute: typeof SupportRoute
  LocaleSupportRoute: typeof LocaleSupportRoute
  DocsSplatRoute: typeof DocsSplatRoute
  DocsIndexRoute: typeof DocsIndexRoute
  LocaleDocsSplatRoute: typeof LocaleDocsSplatRoute
  LocaleDocsIndexRoute: typeof LocaleDocsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale_/support': {
      id: '/$locale_/support'
      path: '/$locale/support'
      fullPath: '/$locale/support'
      preLoaderRoute: typeof LocaleSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale_/docs/': {
      id: '/$locale_/docs/'
      path: '/$locale/docs'
      fullPath: '/$locale/docs/'
      preLoaderRoute: typeof LocaleDocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale_/docs/$': {
      id: '/$locale_/docs/$'
      path: '/$locale/docs/$'
      fullPath: '/$locale/docs/$'
      preLoaderRoute: typeof LocaleDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRoute,
  SupportRoute: SupportRoute,
  LocaleSupportRoute: LocaleSupportRoute,
  DocsSplatRoute: DocsSplatRoute,
  DocsIndexRoute: DocsIndexRoute,
  LocaleDocsSplatRoute: LocaleDocsSplatRoute,
  LocaleDocsIndexRoute: LocaleDocsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
