/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as ApiIndexRouteImport } from './routes/api/index'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as LocaleSupportRouteImport } from './routes/$locale_.support'
import { Route as ApiLangIndexRouteImport } from './routes/api/$lang/index'
import { Route as LocaleDocsIndexRouteImport } from './routes/$locale_.docs.index'
import { Route as LocaleApiIndexRouteImport } from './routes/$locale_.api.index'
import { Route as ApiLangModuleRouteImport } from './routes/api/$lang/$module'
import { Route as LocaleDocsSplatRouteImport } from './routes/$locale_.docs.$'
import { Route as LocaleApiLangIndexRouteImport } from './routes/$locale_.api.$lang.index'
import { Route as LocaleApiLangModuleRouteImport } from './routes/$locale_.api.$lang.$module'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIndexRoute = ApiIndexRouteImport.update({
  id: '/api/',
  path: '/api/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSupportRoute = LocaleSupportRouteImport.update({
  id: '/$locale_/support',
  path: '/$locale/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLangIndexRoute = ApiLangIndexRouteImport.update({
  id: '/api/$lang/',
  path: '/api/$lang/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleDocsIndexRoute = LocaleDocsIndexRouteImport.update({
  id: '/$locale_/docs/',
  path: '/$locale/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleApiIndexRoute = LocaleApiIndexRouteImport.update({
  id: '/$locale_/api/',
  path: '/$locale/api/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLangModuleRoute = ApiLangModuleRouteImport.update({
  id: '/api/$lang/$module',
  path: '/api/$lang/$module',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleDocsSplatRoute = LocaleDocsSplatRouteImport.update({
  id: '/$locale_/docs/$',
  path: '/$locale/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleApiLangIndexRoute = LocaleApiLangIndexRouteImport.update({
  id: '/$locale_/api/$lang/',
  path: '/$locale/api/$lang/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleApiLangModuleRoute = LocaleApiLangModuleRouteImport.update({
  id: '/$locale_/api/$lang/$module',
  path: '/$locale/api/$lang/$module',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRoute
  '/support': typeof SupportRoute
  '/$locale/support': typeof LocaleSupportRoute
  '/docs/$': typeof DocsSplatRoute
  '/api/': typeof ApiIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/$locale/docs/$': typeof LocaleDocsSplatRoute
  '/api/$lang/$module': typeof ApiLangModuleRoute
  '/$locale/api/': typeof LocaleApiIndexRoute
  '/$locale/docs/': typeof LocaleDocsIndexRoute
  '/api/$lang/': typeof ApiLangIndexRoute
  '/$locale/api/$lang/$module': typeof LocaleApiLangModuleRoute
  '/$locale/api/$lang/': typeof LocaleApiLangIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRoute
  '/support': typeof SupportRoute
  '/$locale/support': typeof LocaleSupportRoute
  '/docs/$': typeof DocsSplatRoute
  '/api': typeof ApiIndexRoute
  '/docs': typeof DocsIndexRoute
  '/$locale/docs/$': typeof LocaleDocsSplatRoute
  '/api/$lang/$module': typeof ApiLangModuleRoute
  '/$locale/api': typeof LocaleApiIndexRoute
  '/$locale/docs': typeof LocaleDocsIndexRoute
  '/api/$lang': typeof ApiLangIndexRoute
  '/$locale/api/$lang/$module': typeof LocaleApiLangModuleRoute
  '/$locale/api/$lang': typeof LocaleApiLangIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRoute
  '/support': typeof SupportRoute
  '/$locale_/support': typeof LocaleSupportRoute
  '/docs/$': typeof DocsSplatRoute
  '/api/': typeof ApiIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/$locale_/docs/$': typeof LocaleDocsSplatRoute
  '/api/$lang/$module': typeof ApiLangModuleRoute
  '/$locale_/api/': typeof LocaleApiIndexRoute
  '/$locale_/docs/': typeof LocaleDocsIndexRoute
  '/api/$lang/': typeof ApiLangIndexRoute
  '/$locale_/api/$lang/$module': typeof LocaleApiLangModuleRoute
  '/$locale_/api/$lang/': typeof LocaleApiLangIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/support'
    | '/$locale/support'
    | '/docs/$'
    | '/api/'
    | '/docs/'
    | '/$locale/docs/$'
    | '/api/$lang/$module'
    | '/$locale/api/'
    | '/$locale/docs/'
    | '/api/$lang/'
    | '/$locale/api/$lang/$module'
    | '/$locale/api/$lang/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/support'
    | '/$locale/support'
    | '/docs/$'
    | '/api'
    | '/docs'
    | '/$locale/docs/$'
    | '/api/$lang/$module'
    | '/$locale/api'
    | '/$locale/docs'
    | '/api/$lang'
    | '/$locale/api/$lang/$module'
    | '/$locale/api/$lang'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/support'
    | '/$locale_/support'
    | '/docs/$'
    | '/api/'
    | '/docs/'
    | '/$locale_/docs/$'
    | '/api/$lang/$module'
    | '/$locale_/api/'
    | '/$locale_/docs/'
    | '/api/$lang/'
    | '/$locale_/api/$lang/$module'
    | '/$locale_/api/$lang/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRoute
  SupportRoute: typeof SupportRoute
  LocaleSupportRoute: typeof LocaleSupportRoute
  DocsSplatRoute: typeof DocsSplatRoute
  ApiIndexRoute: typeof ApiIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  LocaleDocsSplatRoute: typeof LocaleDocsSplatRoute
  ApiLangModuleRoute: typeof ApiLangModuleRoute
  LocaleApiIndexRoute: typeof LocaleApiIndexRoute
  LocaleDocsIndexRoute: typeof LocaleDocsIndexRoute
  ApiLangIndexRoute: typeof ApiLangIndexRoute
  LocaleApiLangModuleRoute: typeof LocaleApiLangModuleRoute
  LocaleApiLangIndexRoute: typeof LocaleApiLangIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/': {
      id: '/api/'
      path: '/api'
      fullPath: '/api/'
      preLoaderRoute: typeof ApiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale_/support': {
      id: '/$locale_/support'
      path: '/$locale/support'
      fullPath: '/$locale/support'
      preLoaderRoute: typeof LocaleSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$lang/': {
      id: '/api/$lang/'
      path: '/api/$lang'
      fullPath: '/api/$lang/'
      preLoaderRoute: typeof ApiLangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale_/docs/': {
      id: '/$locale_/docs/'
      path: '/$locale/docs'
      fullPath: '/$locale/docs/'
      preLoaderRoute: typeof LocaleDocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale_/api/': {
      id: '/$locale_/api/'
      path: '/$locale/api'
      fullPath: '/$locale/api/'
      preLoaderRoute: typeof LocaleApiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$lang/$module': {
      id: '/api/$lang/$module'
      path: '/api/$lang/$module'
      fullPath: '/api/$lang/$module'
      preLoaderRoute: typeof ApiLangModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale_/docs/$': {
      id: '/$locale_/docs/$'
      path: '/$locale/docs/$'
      fullPath: '/$locale/docs/$'
      preLoaderRoute: typeof LocaleDocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale_/api/$lang/': {
      id: '/$locale_/api/$lang/'
      path: '/$locale/api/$lang'
      fullPath: '/$locale/api/$lang/'
      preLoaderRoute: typeof LocaleApiLangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale_/api/$lang/$module': {
      id: '/$locale_/api/$lang/$module'
      path: '/$locale/api/$lang/$module'
      fullPath: '/$locale/api/$lang/$module'
      preLoaderRoute: typeof LocaleApiLangModuleRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRoute,
  SupportRoute: SupportRoute,
  LocaleSupportRoute: LocaleSupportRoute,
  DocsSplatRoute: DocsSplatRoute,
  ApiIndexRoute: ApiIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  LocaleDocsSplatRoute: LocaleDocsSplatRoute,
  ApiLangModuleRoute: ApiLangModuleRoute,
  LocaleApiIndexRoute: LocaleApiIndexRoute,
  LocaleDocsIndexRoute: LocaleDocsIndexRoute,
  ApiLangIndexRoute: ApiLangIndexRoute,
  LocaleApiLangModuleRoute: LocaleApiLangModuleRoute,
  LocaleApiLangIndexRoute: LocaleApiLangIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
