// AUTO-GENERATED. DO NOT EDIT.
// Code generated by ./codegen. DO NOT EDIT.
// Any manual changes WILL BE LOST when this file is regenerated.

#pragma once
#include "nativeapi.h"
#include <stdlib.h>
#include <stdint.h>
extern void goReleaseCallback(uintptr_t handle);
static inline void go_release_callback(void* data) {
if (data) { goReleaseCallback(*(uintptr_t*)data); free(data); }
}
static inline native_release_user_data_t go_get_release_callback(void) { return go_release_callback; }
static inline unsigned int go_native_keyboard_event_t_modifier_keys_changed_ModifierKeys(const native_keyboard_event_t* event) { return event->data.modifier_keys_changed.modifier_keys; }
extern void goEvent_native_keyboard_event_t(uintptr_t handle, native_keyboard_event_t* event);
static inline void go_native_keyboard_event_callback_t(const native_keyboard_event_t* event, void* data) { goEvent_native_keyboard_event_t(*(uintptr_t*)data, (native_keyboard_event_t*)event); }
static inline native_keyboard_event_callback_t go_get_native_keyboard_event_callback_t(void) { return go_native_keyboard_event_callback_t; }
extern void goEvent_native_display_event_t(uintptr_t handle, native_display_event_t* event);
static inline void go_native_display_event_callback_t(const native_display_event_t* event, void* data) { goEvent_native_display_event_t(*(uintptr_t*)data, (native_display_event_t*)event); }
static inline native_display_event_callback_t go_get_native_display_event_callback_t(void) { return go_native_display_event_callback_t; }
static inline char* go_native_notification_event_t_activated_Argument(const native_notification_event_t* event) { return event->data.activated.argument; }
extern void goEvent_native_notification_event_t(uintptr_t handle, native_notification_event_t* event);
static inline void go_native_notification_event_callback_t(const native_notification_event_t* event, void* data) { goEvent_native_notification_event_t(*(uintptr_t*)data, (native_notification_event_t*)event); }
static inline native_notification_event_callback_t go_get_native_notification_event_callback_t(void) { return go_native_notification_event_callback_t; }
static inline char* go_native_view_event_t_text_field_changed_Text(const native_view_event_t* event) { return event->data.text_field_changed.text; }
extern void goEvent_native_view_event_t(uintptr_t handle, native_view_event_t* event);
static inline void go_native_view_event_callback_t(const native_view_event_t* event, void* data) { goEvent_native_view_event_t(*(uintptr_t*)data, (native_view_event_t*)event); }
static inline native_view_event_callback_t go_get_native_view_event_callback_t(void) { return go_native_view_event_callback_t; }
static inline native_point_t go_native_window_event_t_moved_NewPosition(const native_window_event_t* event) { return event->data.moved.new_position; }
static inline native_size_t go_native_window_event_t_resized_NewSize(const native_window_event_t* event) { return event->data.resized.new_size; }
static inline native_event_request_t go_native_window_event_t_close_requested_Request(const native_window_event_t* event) { return event->data.close_requested.request; }
static inline native_window_property_t go_native_window_event_t_property_changed_Property(const native_window_event_t* event) { return event->data.property_changed.property; }
static inline native_window_occlusion_state_t go_native_window_event_t_occlusion_changed_OcclusionState(const native_window_event_t* event) { return event->data.occlusion_changed.occlusion_state; }
extern void goEvent_native_window_event_t(uintptr_t handle, native_window_event_t* event);
static inline void go_native_window_event_callback_t(const native_window_event_t* event, void* data) { goEvent_native_window_event_t(*(uintptr_t*)data, (native_window_event_t*)event); }
static inline native_window_event_callback_t go_get_native_window_event_callback_t(void) { return go_native_window_event_callback_t; }
extern void goEvent_native_window_drag_event_t(uintptr_t handle, native_window_drag_event_t* event);
static inline void go_native_window_drag_event_callback_t(const native_window_drag_event_t* event, void* data) { goEvent_native_window_drag_event_t(*(uintptr_t*)data, (native_window_drag_event_t*)event); }
static inline native_window_drag_event_callback_t go_get_native_window_drag_event_callback_t(void) { return go_native_window_drag_event_callback_t; }
static inline native_drag_operation_t go_native_drag_source_event_t_ended_Operation(const native_drag_source_event_t* event) { return event->data.ended.operation; }
extern void goEvent_native_drag_source_event_t(uintptr_t handle, native_drag_source_event_t* event);
static inline void go_native_drag_source_event_callback_t(const native_drag_source_event_t* event, void* data) { goEvent_native_drag_source_event_t(*(uintptr_t*)data, (native_drag_source_event_t*)event); }
static inline native_drag_source_event_callback_t go_get_native_drag_source_event_callback_t(void) { return go_native_drag_source_event_callback_t; }
static inline native_string_list_t go_native_drop_target_event_t_dropped_FilePaths(const native_drop_target_event_t* event) { return event->data.dropped.file_paths; }
static inline char* go_native_drop_target_event_t_dropped_Text(const native_drop_target_event_t* event) { return event->data.dropped.text; }
extern void goEvent_native_drop_target_event_t(uintptr_t handle, native_drop_target_event_t* event);
static inline void go_native_drop_target_event_callback_t(const native_drop_target_event_t* event, void* data) { goEvent_native_drop_target_event_t(*(uintptr_t*)data, (native_drop_target_event_t*)event); }
static inline native_drop_target_event_callback_t go_get_native_drop_target_event_callback_t(void) { return go_native_drop_target_event_callback_t; }
static inline native_menu_id_t go_native_menu_event_t_opened_MenuId(const native_menu_event_t* event) { return event->data.opened.menu_id; }
static inline native_menu_id_t go_native_menu_event_t_closed_MenuId(const native_menu_event_t* event) { return event->data.closed.menu_id; }
static inline native_menu_item_id_t go_native_menu_event_t_item_clicked_ItemId(const native_menu_event_t* event) { return event->data.item_clicked.item_id; }
static inline native_menu_item_id_t go_native_menu_event_t_item_submenu_opened_ItemId(const native_menu_event_t* event) { return event->data.item_submenu_opened.item_id; }
static inline native_menu_item_id_t go_native_menu_event_t_item_submenu_closed_ItemId(const native_menu_event_t* event) { return event->data.item_submenu_closed.item_id; }
extern void goEvent_native_menu_event_t(uintptr_t handle, native_menu_event_t* event);
static inline void go_native_menu_event_callback_t(const native_menu_event_t* event, void* data) { goEvent_native_menu_event_t(*(uintptr_t*)data, (native_menu_event_t*)event); }
static inline native_menu_event_callback_t go_get_native_menu_event_callback_t(void) { return go_native_menu_event_callback_t; }
static inline native_tray_icon_id_t go_native_tray_icon_event_t_clicked_TrayIconId(const native_tray_icon_event_t* event) { return event->data.clicked.tray_icon_id; }
static inline native_tray_icon_id_t go_native_tray_icon_event_t_right_clicked_TrayIconId(const native_tray_icon_event_t* event) { return event->data.right_clicked.tray_icon_id; }
static inline native_tray_icon_id_t go_native_tray_icon_event_t_double_clicked_TrayIconId(const native_tray_icon_event_t* event) { return event->data.double_clicked.tray_icon_id; }
extern void goEvent_native_tray_icon_event_t(uintptr_t handle, native_tray_icon_event_t* event);
static inline void go_native_tray_icon_event_callback_t(const native_tray_icon_event_t* event, void* data) { goEvent_native_tray_icon_event_t(*(uintptr_t*)data, (native_tray_icon_event_t*)event); }
static inline native_tray_icon_event_callback_t go_get_native_tray_icon_event_callback_t(void) { return go_native_tray_icon_event_callback_t; }
static inline char* go_native_shortcut_event_t_registration_failed_ErrorMessage(const native_shortcut_event_t* event) { return event->data.registration_failed.error_message; }
extern void goEvent_native_shortcut_event_t(uintptr_t handle, native_shortcut_event_t* event);
static inline void go_native_shortcut_event_callback_t(const native_shortcut_event_t* event, void* data) { goEvent_native_shortcut_event_t(*(uintptr_t*)data, (native_shortcut_event_t*)event); }
static inline native_shortcut_event_callback_t go_get_native_shortcut_event_callback_t(void) { return go_native_shortcut_event_callback_t; }
static inline int go_native_application_event_t_exiting_ExitCode(const native_application_event_t* event) { return event->data.exiting.exit_code; }
static inline native_event_request_t go_native_application_event_t_quit_requested_Request(const native_application_event_t* event) { return event->data.quit_requested.request; }
extern void goEvent_native_application_event_t(uintptr_t handle, native_application_event_t* event);
static inline void go_native_application_event_callback_t(const native_application_event_t* event, void* data) { goEvent_native_application_event_t(*(uintptr_t*)data, (native_application_event_t*)event); }
static inline native_application_event_callback_t go_get_native_application_event_callback_t(void) { return go_native_application_event_callback_t; }
extern void goCall_native_shortcut_create_with_id_and_accelerator_and_callback_t(uintptr_t handle);
static inline void go_native_shortcut_create_with_id_and_accelerator_and_callback_t(void* data) { goCall_native_shortcut_create_with_id_and_accelerator_and_callback_t(*(uintptr_t*)data); }
static inline native_shortcut_create_with_id_and_accelerator_and_callback_t go_get_native_shortcut_create_with_id_and_accelerator_and_callback_t(void) { return go_native_shortcut_create_with_id_and_accelerator_and_callback_t; }
extern void goCall_native_shortcut_manager_register_callback_t(uintptr_t handle);
static inline void go_native_shortcut_manager_register_callback_t(void* data) { goCall_native_shortcut_manager_register_callback_t(*(uintptr_t*)data); }
static inline native_shortcut_manager_register_callback_t go_get_native_shortcut_manager_register_callback_t(void) { return go_native_shortcut_manager_register_callback_t; }
extern void goCall_native_shortcut_options_callback_t(uintptr_t handle);
static inline void go_native_shortcut_options_callback_t(void* data) { goCall_native_shortcut_options_callback_t(*(uintptr_t*)data); }
static inline native_shortcut_options_callback_t go_get_native_shortcut_options_callback_t(void) { return go_native_shortcut_options_callback_t; }
extern void goCall_native_shortcut_set_callback_t(uintptr_t handle);
static inline void go_native_shortcut_set_callback_t(void* data) { goCall_native_shortcut_set_callback_t(*(uintptr_t*)data); }
static inline native_shortcut_set_callback_t go_get_native_shortcut_set_callback_t(void) { return go_native_shortcut_set_callback_t; }
extern void goCall_native_window_manager_set_will_hide_hook_callback_t(uintptr_t handle, unsigned int arg0);
static inline void go_native_window_manager_set_will_hide_hook_callback_t(unsigned int arg0, void* data) { goCall_native_window_manager_set_will_hide_hook_callback_t(*(uintptr_t*)data, arg0); }
static inline native_window_manager_set_will_hide_hook_callback_t go_get_native_window_manager_set_will_hide_hook_callback_t(void) { return go_native_window_manager_set_will_hide_hook_callback_t; }
extern void goCall_native_window_manager_set_will_show_hook_callback_t(uintptr_t handle, unsigned int arg0);
static inline void go_native_window_manager_set_will_show_hook_callback_t(unsigned int arg0, void* data) { goCall_native_window_manager_set_will_show_hook_callback_t(*(uintptr_t*)data, arg0); }
static inline native_window_manager_set_will_show_hook_callback_t go_get_native_window_manager_set_will_show_hook_callback_t(void) { return go_native_window_manager_set_will_show_hook_callback_t; }
