#pragma once

#include "../src/accessibility_manager.h"
#include "../src/app_runner.h"
#include "../src/display.h"
#include "../src/display_event.h"
#include "../src/display_manager.h"
#include "../src/event.h"
#include "../src/event_dispatcher.h"
#include "../src/geometry.h"
#include "../src/keyboard_event.h"
#include "../src/keyboard_monitor.h"
#include "../src/menu.h"
#include "../src/tray_icon.h"
#include "../src/tray_icon_event.h"
#include "../src/tray_manager.h"
#include "../src/window.h"
#include "../src/window_event.h"
#include "../src/window_manager.h"

// Include necessary headers for C API
#include "../src/capi/accessibility_manager_c.h"
#include "../src/capi/app_runner_c.h"
#include "../src/capi/display_c.h"
#include "../src/capi/display_manager_c.h"
#include "../src/capi/geometry_c.h"
#include "../src/capi/keyboard_monitor_c.h"
#include "../src/capi/menu_c.h"
#include "../src/capi/run_example_app_c.h"
#include "../src/capi/tray_icon_c.h"
#include "../src/capi/tray_manager_c.h"
#include "../src/capi/window_c.h"
#include "../src/capi/window_manager_c.h"
