#pragma once

#ifdef __cplusplus
// C++ API headers
#include "../src/accessibility_manager.h"
#include "../src/application.h"
#include "../src/application_event.h"
#include "../src/autostart.h"
#include "../src/dialog.h"
#include "../src/display.h"
#include "../src/display_event.h"
#include "../src/display_manager.h"
#include "../src/foundation/event.h"
#include "../src/foundation/event_emitter.h"
#include "../src/foundation/geometry.h"
#include "../src/foundation/id_allocator.h"
#include "../src/foundation/keyboard.h"
#include "../src/image.h"
#include "../src/keyboard_event.h"
#include "../src/keyboard_monitor.h"
#include "../src/menu.h"
#include "../src/message_dialog.h"
#include "../src/preferences.h"
#include "../src/secure_storage.h"
#include "../src/shortcut.h"
#include "../src/shortcut_event.h"
#include "../src/shortcut_manager.h"
#include "../src/storage.h"
#include "../src/tray_icon.h"
#include "../src/tray_icon_event.h"
#include "../src/tray_manager.h"
#include "../src/window.h"
#include "../src/window_event.h"
#include "../src/window_manager.h"
#endif

// C API headers (available for both C and C++)
#include "../src/capi/accessibility_manager_c.h"
#include "../src/capi/application_c.h"
#include "../src/capi/autostart_c.h"
#include "../src/capi/display_c.h"
#include "../src/capi/display_manager_c.h"
#include "../src/capi/geometry_c.h"
#include "../src/capi/image_c.h"
#include "../src/capi/keyboard_monitor_c.h"
#include "../src/capi/menu_c.h"
#include "../src/capi/message_dialog_c.h"
#include "../src/capi/preferences_c.h"
#include "../src/capi/secure_storage_c.h"
#include "../src/capi/string_utils_c.h"
#include "../src/capi/tray_icon_c.h"
#include "../src/capi/tray_manager_c.h"
#include "../src/capi/window_c.h"
#include "../src/capi/window_manager_c.h"
