name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        include:
          - os: macos-latest
            platform: macos
          - os: ubuntu-latest
            platform: linux
          - os: windows-latest
            platform: windows

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up CMake
        shell: bash
        run: |
          cmake --version
          if [ "${{ matrix.platform }}" = "linux" ]; then
            sudo apt-get update
            sudo apt-get install -y ninja-build libgtk-3-dev libx11-dev libxi-dev
          fi

      - name: Configure CMake
        shell: bash
        run: |
          mkdir build
          cd build
          if [ "${{ matrix.platform }}" = "windows" ]; then
            cmake .. -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 17 2022"
          else
            cmake .. -DCMAKE_BUILD_TYPE=Release
          fi

      - name: Build Examples
        shell: bash
        run: |
          cd build
          cmake --build . --config Release

      # - name: Upload artifacts
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: examples-${{ matrix.platform }}
      #     path: |
      #       build/examples/*/
      #       !build/examples/*/CMakeFiles/
      #       !build/examples/*/cmake_install.cmake
